version: '3.8'

services:
  user-db:
    image: mysql:8.0
    container_name: user-db
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_ROOT_PASSWORD: root
    ports:
      - '2020:3306'
    expose:
      - '2020'
    volumes:
      - '/mysql/data'